version: '3.8'

services:
  web:
    image: nginx:latest
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=value=db
      - MYSQL_PASSWORD=value=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
